### ISSUE TITLE
Structured Spark Streaming

### ISSUE THREAD

**Issue by Deepak3994** [japila-books/spark-structured-streaming-internals#2]
Hi Jaceklaskowski,

I am working on Structured Spark Streaming. I have few doubts regarding it..

1) How to de-serialize from bytes to string when reading the data from kafka-topic?

2) What is this default schema which we get? (I didnt understand these like what they contain)
  for ex:  
root
 |-- key: binary (nullable = true)
 |-- value: binary (nullable = true)
 |-- topic: string (nullable = true)
 |-- partition: integer (nullable = true)
 |-- offset: long (nullable = true)
 |-- timestamp: timestamp (nullable = true)
 |-- timestampType: integer (nullable = true)

3) Can we write our own schema and map to it, while reading data from the kafka topic ?

It would be a great help for me if you could brief me through this...looking forward for your reply. :)

**Comment by toddleo** [comment]
Hi Deepak,

I can't help to answer this, since I am working on a project with a similar use case. Hope you have solutions not too long after, but still, for the questions,

> 1. How to de-serialize from bytes to string when reading the data from kafka-topic?

You can simply cast `value` column into string:

```
df.select('value cast "string")
```
> 2. What is this default schema which we get? (I didnt understand these like what they contain)

Yes the schema you posted here is the default schema. The payload in your Kafka message stores in `value` column.

> 3. Can we write our own schema and map to it, while reading data from the kafka topic ?

No, unless your data is in JSON format, in this case, you can use `from_json()` to parse the `value` column into a DataFrame. Also see @jaceklaskowski 's [answer on SO](https://stackoverflow.com/a/51838002/9254747).

---

I also suggest you to read through [Structured Streaming + Kafka Integration Guide](https://spark.apache.org/docs/latest/structured-streaming-kafka-integration.html) and [Processing Data in Apache Kafka with Structured Streaming in Apache Spark 2.2](https://databricks.com/blog/2017/04/26/processing-data-in-apache-kafka-with-structured-streaming-in-apache-spark-2-2.html), for basic usage of Spark Structured Streaming, which you may already read at this point of time.

**Comment by jaceklaskowski** [comment]
Closing as the issue has already been answered. Questions should rather be posted at [StackOverflow](https://stackoverflow.com/tags/spark-structured-streaming/info) for wider exposure.
